White labeling/elastic license requirements 17
wazuh/wui pull request #21
Opened 2022-01-26 16:13 UTC by asteriscos

### Summary

Hi Team,

this PR white labels files, classes, styles, etc to Wazuh and it's part of meeting Elastic license requirements.

### Checklist

- [ ] Check against **all themes** for compatibility in both light and dark modes
- [ ] Checked in **mobile**
- [ ] Checked in **Chrome**, **Safari**, **Edge**, and **Firefox**
- [ ] Props have proper **autodocs**
- [ ] Added **[documentation](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md)**
- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for the any docs examples
- [ ] Added or updated **[jest tests](https://github.com/elastic/eui/blob/master/wiki/testing.md)**
- [ ] Checked for **breaking changes** and labeled appropriately
- [ ] Checked for **accessibility** including keyboard-only and screenreader modes
- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry exists and is marked appropriately

2022-01-26 19:46 UTC, mauceballos commented
in the wazuh-wui have some icons, in the dark theme, that should be displayed the another way

please see the screenshot
![header](https://user-images.githubusercontent.com/76791841/151235720-064aa448-0bc8-47bc-bd21-2b9ef3eb0ede.png)

2022-01-27 07:39 UTC, mpRegalado requested changes
## Non source files
There are multiple files under dot folders such as .ci or .github that reference eui and it's repository. Should these still be there?

The docs folder contains many references to the old names. It seems like it is a minified version of the documentation that may not have been updated. Should it be either updated or added to gitignore?

Documents in the wiki still reference eui and its original repository

## Component names
There are still variables and components using the old name scheme

- EuiTextColor
- $euiSize--
- $euiFontSize--
- $euiFontWeight--
- $euiColor--
- $euiTextColor

I would recommentd running a case sensitive serch on the project after addressing the changes in wiki and docs for:
- <Eui
- $eui
- Eui
- eui

This should help locate all instances of tradenames used within the project

## Icons
Review the `/src/components/icon/assets` directory for unused assets or assets inflicting on the license terms.
One should make sure that the elastic assets are removed.
Some of the conflicting files include:
- logo_apm
- logo_app_search
- logo_beats
- logo_business_analytics
- logo_cloud
- logo_cloud_ece
- logo_code
- logo_elasticsearch
- logo_elastic_stack
- logo_enterprise_search
- logo_logging
- logo_logstash
- logo_maps
- logo_metrics
- logo_observability
- logo_security
- logo_site_search
- logo_workplace_search

2022-01-28 15:27 UTC, mpRegalado requested changes

2022-01-28 15:27 UTC, mpRegalado commented on NOTICE
> +WUI
This file is meant to have attribution notices for another used in the project, not another file to store the license in.
You must check the NOTICE file present in the EUI repository for the upstream version. If the notices there refer to libraries that are still used, copy them.
Also, this may be a good place to include attributions to third party libraries that require it, such as FontAwesome if any of their icons are included.

2022-01-31 10:22 UTC, Desvelao commented on NOTICE
> +WUI
The licenses are corresponding to `@elastic/eui` and `@elasic/charts` notices, not the library itself ( `@wazuh/wui`). 

The original `NOTICE` file contains the license for each notice https://github.com/elastic/eui/blob/v29.3.2/NOTICE.txt

2022-01-31 11:10 UTC, mpRegalado commented on NOTICE
> +WUI
Apologies, you are right, I had in mind a NOTICE file for a different project and was surprised to find this one to be so long.

2022-01-31 16:03 UTC, Desvelao commented
## Changes
- Fixed the `logoWazuh` icon doesn't take into account the selected theme
- Removed logos for `apps`, `ml` and some for `vis` related to Elastic products
- Removed video explaining how to use the library
- Removed the `NEW` tags
- Renamed `kbl` icons to `qry`
- Updated the tests
- Updated the `docs` folder

## TODO
- [ ] Replace the `qry` icons (React.js component and SVG). We need the assets.

2022-02-01 17:04 UTC, Desvelao commented
## Changes
- Replaced the `qry` icons
  - Components
  - SVG

2022-02-02 19:26 UTC, matiasmoreno876 approved these changes
CR LGTM 
TEST LGTM

2022-02-07 13:26 UTC, mpRegalado approved these changes
LGTM: Great job!

2022-02-07 14:40 UTC, merged